<Project Sdk="MSTest.Sdk">
  <PropertyGroup>
    <TestingExtensionsProfile>Default</TestingExtensionsProfile>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\WindowsDownloadManager.CrashTestHost\WindowsDownloadManager.CrashTestHost.csproj" ReferenceOutputAssembly="false" />
    <ProjectReference Include="..\..\src\WindowsDownloadManager.Application\WindowsDownloadManager.Application.csproj" />
    <ProjectReference Include="..\..\src\WindowsDownloadManager.Domain\WindowsDownloadManager.Domain.csproj" />
    <ProjectReference Include="..\..\src\WindowsDownloadManager.Network\WindowsDownloadManager.Network.csproj" />
    <ProjectReference Include="..\..\src\WindowsDownloadManager.Persistence\WindowsDownloadManager.Persistence.csproj" />
    <ProjectReference Include="..\..\src\WindowsDownloadManager.Storage\WindowsDownloadManager.Storage.csproj" />
  </ItemGroup>
</Project>
